
import React from 'react';

interface TermsOfServiceProps {
    onClose?: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onClose }) => {
    return (
        <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 20px', fontFamily: 'sans-serif', lineHeight: '1.6' }}>
            <h1 style={{ borderBottom: '1px solid #ddd', paddingBottom: '10px' }}>Terms of Service</h1>
            <p style={{ color: '#666', fontSize: '0.9em' }}>Last Updated: {new Date().toLocaleDateString()}</p>

            <h2>1. Acceptance of Terms</h2>
            <p>
                By accessing and using this Family Tree Application, you agree to be bound by these Terms of Service.
                This service is provided exclusively for the members of our family group.
            </p>

            <h2>2. Eligibility and Access</h2>
            <p>
                Access to this application is by invitation only. You must be a recognized family member with an email address
                pre-configured in the system to log in. Unauthorized access attempts are strictly prohibited.
            </p>

            <h2>3. User Responsibilities</h2>
            <p>
                As a member of this close-knit community, you agree to:
            </p>
            <ul>
                <li><strong>Accuracy:</strong> Ensure that any information you add or edit about yourself is accurate.</li>
                <li><strong>Respect:</strong> Respect the privacy and sensitivities of other family members. Do not share information about others outside this closed group without their explicit consent.</li>
                <li><strong>Security:</strong> Maintain the confidentiality of your login credentials to protect the group's data.</li>
            </ul>

            <h2>4. Content and Mutual Trust</h2>
            <p>
                The content on this platform is user-generated by family members.
                <strong>"Information shared is shared within the group with mutual trust."</strong>
            </p>
            <ul>
                <li>You acknowledge that other family members can view the information you choose to share.</li>
                <li>You retain the right to remove any sensitive information from your specific profile if you do not wish for it to be visible.</li>
            </ul>

            <h2>5. Modifications to Service</h2>
            <p>
                The administrators reserve the right to modify or discontinue the service (or any part thereof) with or without notice.
                We may also update these terms from time to time to reflect changes in our community guidelines.
            </p>

            <h2>6. Contact</h2>
            <p>
                For any inquiries regarding these terms, please reach out to the family administrator.
            </p>

            <div style={{ marginTop: '40px', textAlign: 'center' }}>
                <button
                    onClick={() => {
                        if (onClose) {
                            onClose();
                        } else {
                            window.location.hash = '';
                            window.location.reload();
                        }
                    }}
                    style={{
                        padding: '10px 20px',
                        backgroundColor: '#007bff',
                        color: 'white',
                        border: 'none',
                        borderRadius: '5px',
                        cursor: 'pointer',
                        fontSize: '1em'
                    }}
                >
                    Back to Home
                </button>
            </div>
        </div>
    );
};

export default TermsOfService;
